# Generated by Django 3.0.8 on 2020-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='output',
        ),
        migrations.AddField(
            model_name='site',
            name='lfi_status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
