# Generated by Django 3.0.8 on 2020-08-09 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vuln_scanner', '0006_auto_20200809_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
